### ISSUE TITLE
[crash] video ,选择 2 fps , 之后切换到图片帧， 此时crash 

### ISSUE THREAD

**Issue by betty200744** [ufo22940268/Gifer#54]

**Comment by ufo22940268** [comment]
When recreating play item, edit page should not accept other user interactions. But user can go back to previous activity.

**Comment by ufo22940268** [comment]
This issue happens, because the 2fps interval is quit difference from other fps, it will generate new cache files. So if user open frame view controller when the image player item is creating, it will crash.
