### ISSUE TITLE
编辑表情的时候崩溃

### ISSUE THREAD

**Issue by ufo22940268** [ufo22940268/Gifer#81]
从线上日志上看， 发现有用户在添加表情的完了之后返回Edit Page的时候崩溃了

@betty200744 帮忙重现， 我自己试了好多次重现不了

**Comment by ufo22940268** [comment]
![image](https://user-images.githubusercontent.com/848704/64498791-c2906780-d2e8-11e9-974c-ec355f15aeb5.png)

**Comment by ufo22940268** [comment]
我也有在iphone 6s的模拟器上试过，发现重现不了

**Comment by betty200744** [comment]
workforme in version 1.16.0
